### ISSUE TITLE
requirements.txt Installation command does not work

### ISSUE THREAD

**Issue by hrn4n** [cosme12/SimpleCoin#10]
The readme suggests running the following command to install the project dependencies

```
pip install requirements.txt
```

But doing that only returns the following error:

```
$ pip install requirements.txt
Collecting requirements.txt
  Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt
```

A solution I found for this was changing the command to the following

```
pip install `cat requirements.txt`
```

And then it worked fine, perhaps the readme should be updated?

**Comment by cosme12** [comment]
Oh, you are right. The proper way is ```pip install -r requirements.txt```

**Comment by nobody5050** [comment]
Typing to be able to come back
