### ISSUE TITLE
wallet.py doesn't work on MacOS!

### ISSUE THREAD

**Issue by mishushakov** [cosme12/SimpleCoin#23]
Hey, i tried executing wallet.py, basically i can not choose any available options, if i press 1 then enter, nothing happens :( does it only run on windows?

**Comment by cosme12** [comment]
Are you using python 2.7? Python 3 should work as expected.

**Comment by cosme12** [comment]
Probably something like this? 
![input bug](https://k60.kn3.net/D44470AAF.gif)

**Comment by MishUshakov** [comment]
Alright, i will try with python3! Thank you for your effort!

**Comment by Aareon** [comment]
@MishUshakov has the error disappeared after using Python 3?

**Comment by terminalnode** [comment]
I'm also on macOS (High Sierra 10.13.6) and tried this out. It seems to work for me. I was able to generate a new wallet and check transactions.
<img width="1123" alt="capture d ecran 2018-11-05 a 12 03 55" src="https://user-images.githubusercontent.com/2683344/47994578-fca24300-e0f2-11e8-8a02-2a7c90c28786.png">
<img width="542" alt="capture d ecran 2018-11-05 a 12 04 14" src="https://user-images.githubusercontent.com/2683344/47994579-fca24300-e0f2-11e8-947b-d337f512398d.png">

**Comment by terminalnode** [comment]
"Press any key to exit..." is the only thing that doesn't work. I can't just use any key, it has to be enter it seems like.

**Comment by Pineapple6** [comment]
That's easy to solve, since we only need to change "Press any key" to "Press ENTER"

**Comment by cosme12** [comment]
>           That's easy to solve, since we only need to change "Press any key" to "Press ENTER"

Sorry guys, I have been (and still are) really busy. So feel free to push that small fix!

**Comment by catalinpit** [comment]
claim

**Comment by catalinpit** [comment]
@cosme12 fixed the typo
