### ISSUE TITLE
The doubt of 'start_time' assignment at line 77 in the mainer.py file

### ISSUE THREAD

**Issue by zhuofanxu** [cosme12/SimpleCoin#34]
![2018-03-12 15 39 36](https://user-images.githubusercontent.com/3413186/37292658-4dfc9438-264c-11e8-99e7-1a0c7dc94d71.png)

**Comment by cosme12** [comment]
The % checks the remaining of the division between x and 60. So lets say in line 79 we have 110%60 that gives us 50 so the condition is not meet. On the other hand if we have 120%60 that gives us 0 (the division between 120 and 60 is 2 but the remaining is 0) so the condition is satisfied. This work for any multiplus (not sure if that is the word) of 60. Example: 60,120,180,240,300... and so on. Hope that clears your doubt if that was the question.

**Comment by zhuofanxu** [comment]
Yea. the condition itself at 79 is okay. what i mean is that you assign time.time() to 'start_time' at line 72 first time and at line 77 for the second time. The second assignment make the if condition expression always equal to 0. not the 60,120,180,240....

**Comment by zhuofanxu** [comment]
yes

**Comment by cosme12** [comment]
Feel free to push a pull request to [v1.1.0 branch](https://github.com/cosme12/SimpleCoin/tree/v1.1.0) so I can add it and you get listed as collaborator. Thanks for spotting the bug!
