### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by Thakur15021** [cosme12/SimpleCoin#55]
![SimpleCoin](https://user-images.githubusercontent.com/19483250/72679060-4129bc80-3ab4-11ea-8b6a-c3e131777453.png)

Hey guys I am new to using python and I keep getting this error. I am not sure what module is being referred too? Any help would be great. Thanks!

**Comment by cosme12** [comment]
Try `python miner.py`.

**Comment by Thakur15021** [comment]
@cosme12 Yes! That worked. Thank you!

**Comment by cosme12** [comment]
No problem 👍🏼
