### ISSUE TITLE
I Get An Error When i'm Tryings to launch Wallet.py Saying ModuleNotFoundError: No module named 'requests' and for ecdsa

### ISSUE THREAD

**Issue by casparzzz123** [cosme12/SimpleCoin#85]
Hey When Im trying To Launch Wallet.py I Get This Error ModuleNotFoundError: No module named 'requests' And I Get This Error Also ModuleNotFoundError: No module named 'ecdsa' Can Someone Help Me Or Fix This Bug

**Comment by cosme12** [comment]
Try doing ```pip install -r requirements.txt```
